# Generated by Django 3.2.5 on 2021-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newSAEsite', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='online', max_length=200),
        ),
    ]
