# Generated by Django 3.2.6 on 2021-09-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newSAEsite', '0004_auto_20210829_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024')], default=2022),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('MANAGEMENT', 'Management'), ('TECHNICAL-ROBOTICS', 'Technical-Robotics'), ('TECHNICAL-AUTOMOBILE', 'Technical-Automobile'), ('WEBD', 'Web Developement'), ('GRAPHICS', 'Graphics and Photography'), ('NDORS', 'NDORS')], default='FIRST', max_length=20),
        ),
    ]
