# Generated by Django 3.2.6 on 2021-11-28 09:43

from django.db import migrations, models
import newSAEsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('newSAEsite', '0005_auto_20210915_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='baja_pics', validators=[newSAEsite.models.validate_image_size])),
                ('post', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('MANAGEMENT', 'Management'), ('MANAGEMENT AND CONTENT WRITING', 'Management-Content'), ('TECHNICAL-ROBOTICS', 'Technical-Robotics'), ('TECHNICAL-AUTOMOBILE', 'Technical-Automobile'), ('WEB DEVELOPMENT', 'WebD'), ('GRAPHICS DESIGNING AND VIDEOGRAPHY', 'Graphics'), ('NDORS', 'NDORS')], default='FIRST', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('VICE PRESIDENT', 'Vice President'), ('GENERAL SECRETARY', 'General Secretary'), ('TREASURER', 'Treasurer'), ('CONVENER', 'Convener'), ('TECH HEAD', 'Tech Head'), ('DESIGN HEAD', 'Design Head'), ('WEBD HEAD', 'web D'), ('PUBLIC RELATIONS HEAD', 'Public relations Head'), ('CREATIVE HEAD', 'Creative Head'), ('SPONSORSHIP HEAD', 'Sponsorship Head'), ('ACCOMODATION,TRAVEL AND HOSPITALITY HEAD', 'Accomodation,travel and Hospitality Head'), ('CORPORATE COMMUNICATION HEAD', 'Head of Corporate Communication'), ('OPERATIONS HEAD', 'Operations Head'), ('BAJA COORDINATOR', 'Baja coordinator'), ('WORKSHOP HEAD', 'Workshop Head'), ('EVENTS HEAD', 'Events Head'), ('EVENTS AND FEST COORDINATOR', 'Events and Fest coordinator'), ('LOGISTIC HEAD', 'Logistic Head'), ('NONE', 'None')], default='None', max_length=40),
        ),
    ]
