# Generated by Django 3.2.6 on 2022-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newSAEsite', '0006_auto_20211128_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch',
            field=models.IntegerField(choices=[(2023, '2023'), (2024, '2024'), (2025, '2025')], default=2023),
        ),
    ]
