# Generated by Django 3.2.6 on 2022-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newSAEsite', '0007_alter_profile_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('VICE PRESIDENT', 'Vice President'), ('GENERAL SECRETARY', 'General Secretary'), ('TREASURER', 'Treasurer'), ('CONVENER', 'Convener'), ('TECH HEAD', 'Tech Head'), ('DESIGN HEAD', 'Design Head'), ('WEBD HEAD', 'webD Head'), ('PUBLIC RELATIONS HEAD', 'Public relations Head'), ('CREATIVE HEAD', 'Creative Head'), ('SPONSORSHIP HEAD', 'Sponsorship Head'), ('ACCOMODATION,TRAVEL AND HOSPITALITY HEAD', 'Accomodation,travel and Hospitality Head'), ('CORPORATE COMMUNICATION HEAD', 'Head of Corporate Communication'), ('OPERATIONS HEAD', 'Operations Head'), ('BAJA COORDINATOR', 'Baja coordinator'), ('WORKSHOP HEAD', 'Workshop Head'), ('EVENTS HEAD', 'Events Head'), ('EVENTS AND FEST COORDINATOR', 'Events and Fest coordinator'), ('LOGISTIC HEAD', 'Logistic Head'), ('Co CONVENOR', 'Co convenor'), ('ASSISTANT GENERAL SECRETARY', 'Assistant General Secretary'), ('AUTOMOBILE HEAD', 'Automobile head'), ('NONE', 'None')], default='None', max_length=40),
        ),
    ]
