# Generated by Django 3.2.6 on 2022-07-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newSAEsite', '0012_alter_profile_post_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('post_order', 'first_name')},
        ),
    ]
